In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [9]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones(4)

array([1., 1., 1., 1.])

In [22]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.rand(5)

array([0.97544471, 0.6868624 , 0.87441109, 0.59426186, 0.67723555])

In [27]:
np.random.randn(4,4)

array([[ 0.50411866,  0.34029425, -0.92461397, -0.24252732],
       [-0.51561795, -0.47472135, -0.85878047, -2.515131  ],
       [-1.19265821,  0.58031645, -1.70117235,  0.87309957],
       [-0.66601837,  0.47634107,  0.35654685,  0.84918264]])

In [29]:
np.random.randint(1,100,10)

array([76, 73, 97, 14, 44, 50, 27, 10, 20, 31])

In [30]:
arr = np.arange(25)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
ranarr = np.random.randint(0,50,10)

In [40]:
ranarr

array([16, 48,  2,  6, 14, 14, 39, 34,  0, 28])

In [41]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
ranarr.max()

48

In [45]:
ranarr.min()

0

In [46]:
ranarr

array([16, 48,  2,  6, 14, 14, 39, 34,  0, 28])

In [47]:
ranarr.argmax()

1

In [48]:
ranarr.argmin()

8

In [49]:
arr.shape

(25,)

In [50]:
arr = arr.reshape(5,5)

In [51]:
arr.shape

(5, 5)

In [52]:
arr.dtype

dtype('int64')

In [53]:
from numpy.random import randint

In [54]:
randint(2,11)

3

In [55]:
arr = np.arange(0,11)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr[8]

8

In [58]:
arr[1:5]

array([1, 2, 3, 4])

In [59]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [60]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [70]:
arr = np.arange(0,11)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
slice_of_arr = arr[0:6]

In [73]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [74]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [75]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [76]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [77]:
arr_2d[0][0]

5

In [78]:
arr_2d[0]

array([ 5, 10, 15])

In [80]:
arr_2d[1][1]

25

In [81]:
arr_2d[2][1]

40

In [82]:
arr_2d[0,0]

5

In [83]:
arr_2d[1,2]

30

In [84]:
arr_2d[1][2]

30

In [85]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [86]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [87]:
arr = np.arange(1,11)

In [88]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [90]:
bool_arr = arr > 5

In [91]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [92]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [93]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [94]:
arr[arr<3]

array([1, 2])

In [95]:
arr_2d = np.arange(50).reshape(5,10)

In [96]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [100]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [101]:
arr_2d[3:5,7:10]

array([[37, 38, 39],
       [47, 48, 49]])

In [102]:
arr = np.arange(0,11)

In [103]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [105]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [106]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [107]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
arr / arr

/var/folders/qy/rkcprdl56yq_2s5cxp0jp_m80000gn/T/ipykernel_37787/3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [110]:
1 / arr

/var/folders/qy/rkcprdl56yq_2s5cxp0jp_m80000gn/T/ipykernel_37787/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [111]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [112]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [113]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [114]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [115]:
np.max(arr)

10

In [116]:
np.min(arr)

0

In [117]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [118]:
np.log(arr)

/var/folders/qy/rkcprdl56yq_2s5cxp0jp_m80000gn/T/ipykernel_37787/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])